variable "project_name" {}
variable "environment" {}
variable "vpc_id" {}
variable "public_subnet" {}
variable "private_subnet" {}
variable "key_name" {}
variable "instance_type" {}
variable "ami_id" {}
variable "my_ip" {}
